# Generated by Django 4.1.1 on 2022-12-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('griffinskitchen', '0009_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
